# Generated by Django 5.2.1 on 2025-06-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_wallet_balance_walletfundrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfundrequest',
            name='reference_number',
            field=models.TextField(blank=True, help_text='Enter full bank or online receipt text or reference number', null=True),
        ),
    ]
