# Generated by Django 5.2.1 on 2025-07-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_walletfundrequest_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='timezone',
            field=models.CharField(default='Asia/Colombo', max_length=50),
        ),
    ]
