# Generated by Django 5.2.1 on 2025-07-18 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_auto_sys',
            field=models.BooleanField(default=False),
        ),
    ]
