# Generated by Django 5.2.4 on 2025-07-21 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_is_auto_sys'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletfundrequest',
            name='wallet_type',
            field=models.CharField(choices=[('MAIN', 'Main'), ('SECWAL', 'Secwal')], default='MAIN', max_length=10),
        ),
    ]
