# Generated by Django 5.2.4 on 2025-07-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_profile_referral_code_profile_referral_reward_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
