# Generated by Django 5.2.4 on 2025-07-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_profile_referral_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referrer',
        ),
    ]
