# Generated by Django 5.2.4 on 2025-07-21 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_remove_profile_referrer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referral_code',
        ),
    ]
