# Generated by Django 5.2.4 on 2025-07-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_referrals'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sec_wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
