# Generated by Django 5.2.4 on 2025-07-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_profile_sec_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet2_locked',
            field=models.BooleanField(default=False),
        ),
    ]
