# Generated by Django 5.2.4 on 2025-07-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_profile_wallet2_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='referrals',
            name='referral_reward_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
