# Generated by Django 5.2.4 on 2025-08-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_profile_refz_referrer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletfundrequest',
            name='request_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
    ]
