# Generated by Django 5.2.4 on 2025-08-20 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_profile_verification_code_alter_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=45),
        ),
    ]
