# Generated by Django 5.2.4 on 2025-08-20 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_alter_profile_rating'),
    ]

    operations = [
    ]
