# Generated by Django 5.2.4 on 2025-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20250820_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fake_game_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(default=450),
        ),
    ]
